### PR TITLE
Add test data for Keycloak

### PR DESCRIPTION
**Pull request by robojones**
Part of Gamify-IT/issues#193

## How to test this

1. Clone <https://github.com/Gamify-IT/landing-page>
2. Use `docker-compose up` (the docker-compose is currently configured to use the test-data from this branch)
3. Go to <http://localhost:80>
4. Check if you can log in with user `student` password `student`

### CODE REVIEW

**Comment by delvh** [comment]
I mean, I can log in.
But apart from that **nothing** happens?
Is that really intended?

**Comment by delvh** [comment]
image

**Comment by delvh** [comment]
Ah, should here be the redirect to the overworld?
And how can a lecturer/ admin then access the UI keycloak should offer as well?

**Comment by delvh** [comment]
And how do I switch to the `KeyCloak` realm so that I can test the `admin` account?

**Comment by madebyTimo** [comment]
Which UI of keycloak should be there for a lecturer?
The admin UI is accessible at [http://localhost/keycloak/admin/master/console/](http://localhost/keycloak/admin/master/console/)

**Comment by madebyTimo** [comment]
> I mean, I can log in. But apart from that **nothing** happens? Is that really intended?

This PR is only about the keycloak specific test-data. The functionality of the the landing page is not part of it.
Please correct me if I'm wrong @robojones

**Comment by delvh** [comment]
Agree with @madebyTimo, it would probably be a good idea to add a third realm `lecturer`, and to rename the realm `master/keycloak` to `admin` if possible.

Edit: Ok, apparently the master realm cannot be renamed.

**Comment by madebyTimo** [comment]
No a realm for lecturers isn't a good idea. In my Opinion we should create a group for lecturers.
All our users should be in the `Gamify-IT` realm

**Comment by madebyTimo** [comment]
Have we already agreed on how much authorization we want to do in the Stupro?

**Comment by delvh** [comment]
Okay, you know more than I about keycloak.
I thought realms and groups would have been synonyms.
But it makes sense to separate them from an implementation viewpoint.
If you think a group suffices then so be it.

**Comment by delvh** [comment]
> Have we already agreed on how much authorization we want to do in the Stupro?

The minimal amount possible so that it runs and doesn't allow to hijack the instance?

**Review by delvh — APPROVED** [review]

**Review by madebyTimo — APPROVED** [review]
Well done.
Perfectly adequate for the current requirements. Settings in keycloak look good.
If we agree to prevent students to access the lecturer interface a group therefore should be added.

**Comment by madebyTimo** [comment]
> The minimal amount possible so that it runs and doesn't allow to hijack the instance?

I mean it is possible to make the lecturer-interface only accessible from a secured network and to allow all users access to every course.

In my opinion it would be a good compromise to ensure that only lecturers can access the lecturer-interface but to allow all users access to every course.

**Comment by delvh** [comment]
Absolutely agreed.
That was also my intention with `as little as necessary`.

**Pull request merged**
