### PR TITLE
add postgres/login/default.sql with a test user

### PR DESCRIPTION
**Pull request by robojones**
Part of Gamify-IT/issues#200

# How to test this

- clone the overworld-backend repository
- checkout the branch `feature/dummy-data`
- go into the `docker-compose.yaml` file
- Replace
  ```
  setup:
    container_name: setup
    image: ghcr.io/gamify-it/test-data:latest
    pull_policy: always
    restart: on-failure
    environment:
      POSTGRES_SETUP: >
        login/default.sql
        overworld/default.sql
  ```
  with
  ```
  setup:
    container_name: setup
    image: ghcr.io/gamify-it/test-data:feature-login-dataset
    pull_policy: always
    restart: on-failure
    environment:
      POSTGRES_SETUP: >
        login/default.sql
        overworld/default.sql
  ```
  to use the data container from this branch
- run `docker-compose up`
- go to http://localhost
- try to log in with user `test` password `test`

### CODE REVIEW

**Review by cdingm — APPROVED** [review]
the login works for me with the given name and password

is it intended that setup isnt running?
image

**Comment by robojones** [comment]
Yup, it should exit with code 0 after initializing the databases

**Comment by madebyTimo** [comment]
The setup container only puts the dumps into the databases and stops afterwards. So it is intended that setup isn't running after a short time after the startup

**Review by madebyTimo — APPROVED** [review]
well done

**Pull request merged**
